### ISSUE TITLE
Navbar on mobile

### ISSUE THREAD

**Issue by PlayLikeNeverB4** [lisudoku/lisudoku_frontend#43]
On small screen sizes we show this dropdown in the navbar.

<img width="716" alt="Screenshot 2023-02-24 at 15 46 33" src="https://user-images.githubusercontent.com/6545554/221194232-4fe2a83b-fd51-427f-b8d6-3e0dd42f0135.png">

We should close it when the user clicks on one of the menu options or when user clicks outside.

**Comment by lautaromugas8** [comment]
Hey, can I work on this?

**Comment by PlayLikeNeverB4** [comment]
@lautaromugas8 Welcome! Feel free to tackle any of the issues.
